services:
  nwc:
    build: .
    ports:
      - 8080:8080
    environment:
      - QUART_CONFIG=configs/local_docker.py
      - QUART_APP=nwc_backend
      - QUART_ENV=development
      - QUART_DEBUG=True
      - QUART_RUN_PORT=8080
