"""initial tables

Revision ID: 0067f522683a
Revises: 
Create Date: 2024-10-01 14:58:11.136191

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql.json import JSONB

from alembic import op
from nwc_backend.db import UUID, DateTime, DBCurrency

# revision identifiers, used by Alembic.
revision: str = "0067f522683a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_app",
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("VERIFIED", "INVALID", "UNKNOWN", name="nip05verificationstatus"),
            nullable=True,
        ),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", name="client_app_unique_client_id"),
    )
    op.create_table(
        "user",
        sa.Column("vasp_user_id", sa.String(length=255), nullable=False),
        sa.Column("uma_address", sa.String(length=255), nullable=False),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uma_address", name="user_unique_uma_address"),
        sa.UniqueConstraint("vasp_user_id", name="user_unique_vasp_user_id"),
    )
    op.create_table(
        "nwc_connection",
        sa.Column("user_id", UUID(), nullable=False),
        sa.Column("client_app_id", UUID(), nullable=True),
        sa.Column("custom_name", sa.String(length=255), nullable=True),
        sa.Column(
            "granted_permissions_groups",
            sa.JSON().with_variant(JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("long_lived_vasp_token", sa.String(length=1024), nullable=False),
        sa.Column("connection_expires_at", sa.Integer(), nullable=True),
        sa.Column("budget_currency", DBCurrency(), nullable=False),
        sa.Column("spending_limit_id", UUID(), nullable=True),
        sa.Column("nostr_pubkey", sa.String(length=255), nullable=True),
        sa.Column("hashed_refresh_token", sa.String(length=1024), nullable=True),
        sa.Column("authorization_code", sa.String(length=1024), nullable=True),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=True),
        sa.Column("code_challenge", sa.String(length=1024), nullable=True),
        sa.Column("access_token_expires_at", sa.Integer(), nullable=True),
        sa.Column("refresh_token_expires_at", sa.Integer(), nullable=True),
        sa.Column("authorization_code_expires_at", sa.Integer(), nullable=True),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "client_app_id IS NOT NULL OR custom_name IS NOT NULL",
            name="check_client_app_or_custom_name",
        ),
        sa.ForeignKeyConstraint(
            ["client_app_id"],
            ["client_app.id"],
            name="nwc_connection_client_app_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="nwc_connection_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "authorization_code", name="nwc_connection_unique_authorization_code"
        ),
        sa.UniqueConstraint(
            "hashed_refresh_token", name="nwc_connection_unique_hashed_refresh_token"
        ),
        sa.UniqueConstraint("nostr_pubkey", name="nwc_connection_unique_nostr_pubkey"),
    )
    op.create_table(
        "nip47_request",
        sa.Column("nwc_connection_id", UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "PAY_INVOICE",
                "MAKE_INVOICE",
                "LOOKUP_INVOICE",
                "GET_BALANCE",
                "GET_BUDGET",
                "GET_INFO",
                "LIST_TRANSACTIONS",
                "PAY_KEYSEND",
                "LOOKUP_USER",
                "FETCH_QUOTE",
                "EXECUTE_QUOTE",
                "PAY_TO_ADDRESS",
                name="nip47requestmethod",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "params",
            sa.JSON().with_variant(JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("response_event_id", sa.String(length=255), nullable=True),
        sa.Column(
            "response_result",
            sa.JSON().with_variant(JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "response_error_code",
            sa.Enum(
                "RATE_LIMITED",
                "NOT_IMPLEMENTED",
                "INSUFFICIENT_BALANCE",
                "PAYMENT_FAILED",
                "NOT_FOUND",
                "QUOTA_EXCEEDED",
                "RESTRICTED",
                "UNAUTHORIZED",
                "INTERNAL",
                "OTHER",
                name="errorcode",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nwc_connection_id"],
            ["nwc_connection.id"],
            name="nip47_request_nwc_connection_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", name="nip47_request_unique_event_id"),
    )
    op.create_table(
        "spending_limit",
        sa.Column("nwc_connection_id", UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "YEARLY",
                "NONE",
                name="spendinglimitfrequency",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("start_time", DateTime(), nullable=False),
        sa.Column("end_time", DateTime(), nullable=True),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nwc_connection_id"],
            ["nwc_connection.id"],
            initially="DEFERRED",
            deferrable=True,
            name="spending_limit_nwc_connection_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "nwc_connection_spending_limit_id_fkey",
            "spending_limit",
            ["spending_limit_id"],
            ["id"],
            initially="DEFERRED",
            deferrable=True,
        )
    op.create_table(
        "payment_quote",
        sa.Column("nip47_request_id", UUID(), nullable=False),
        sa.Column("receiver_address", sa.String(length=200), nullable=False),
        sa.Column("payment_hash", sa.String(length=255), nullable=False),
        sa.Column("sending_currency_code", sa.String(length=3), nullable=False),
        sa.Column("sending_currency_amount", sa.BigInteger(), nullable=False),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="payment_quote_nip47_request_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_hash", name="payment_quote_unique_payment_hash"),
    )
    op.create_table(
        "spending_cycle",
        sa.Column("spending_limit_id", UUID(), nullable=False),
        sa.Column("limit_amount", sa.BigInteger(), nullable=False),
        sa.Column("start_time", DateTime(), nullable=False),
        sa.Column("end_time", DateTime(), nullable=True),
        sa.Column("total_spent", sa.BigInteger(), nullable=False),
        sa.Column("total_spent_on_hold", sa.BigInteger(), nullable=False),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["spending_limit_id"],
            ["spending_limit.id"],
            name="spending_cycle_spending_limit_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("spending_cycle", schema=None) as batch_op:
        batch_op.create_index(
            "spending_cycle_spending_limit_id_start_time_unique_idx",
            ["spending_limit_id", "start_time"],
            unique=True,
        )

    op.create_table(
        "outgoing_payment",
        sa.Column("nip47_request_id", UUID(), nullable=False),
        sa.Column("nwc_connection_id", UUID(), nullable=False),
        sa.Column("quote_id", UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                name="paymentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("sending_currency_code", sa.String(length=3), nullable=False),
        sa.Column("sending_currency_amount", sa.BigInteger(), nullable=False),
        sa.Column("receiver", sa.String(length=10240), nullable=False),
        sa.Column(
            "receiver_type",
            sa.Enum(
                "LUD16",
                "BOLT12",
                "BOLT11",
                "NODE_PUBKEY",
                name="receivingaddresstype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("spending_cycle_id", UUID(), nullable=True),
        sa.Column("estimated_budget_currency_amount", sa.BigInteger(), nullable=True),
        sa.Column("budget_on_hold", sa.BigInteger(), nullable=True),
        sa.Column("settled_budget_currency_amount", sa.BigInteger(), nullable=True),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="outgoing_payment_nip47_request_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["nwc_connection_id"],
            ["nwc_connection.id"],
            name="outgoing_payment_nwc_connection_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["payment_quote.id"],
            name="outgoing_payment_quote_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["spending_cycle_id"],
            ["spending_cycle.id"],
            name="outgoing_payment_spending_cycle_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outgoing_payment", schema=None) as batch_op:
        batch_op.create_index(
            "outgoing_payment_connection_id_status_created_at_idx",
            ["nwc_connection_id", "status", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outgoing_payment", schema=None) as batch_op:
        batch_op.drop_index("outgoing_payment_connection_id_status_created_at_idx")

    op.drop_table("outgoing_payment")
    with op.batch_alter_table("spending_cycle", schema=None) as batch_op:
        batch_op.drop_index("spending_cycle_spending_limit_id_start_time_unique_idx")

    op.drop_table("spending_cycle")
    op.drop_table("payment_quote")
    op.drop_table("spending_limit")
    op.drop_table("nip47_request")
    op.drop_table("nwc_connection")
    op.drop_table("user")
    op.drop_table("client_app")
    # ### end Alembic commands ###
