"""Create oauth models

Revision ID: 0fc63b5c0f6c
Revises: 556f426aa133
Create Date: 2024-08-12 09:01:11.011607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from nwc_backend.db import UUID

# revision identifiers, used by Alembic.
revision: str = "0fc63b5c0f6c"
down_revision: Union[str, None] = "15d5b0a9bde9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_app",
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("client_metadata", sa.Text(), nullable=True),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", name="unique_client_id"),
    )
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("access_token", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(
            sa.Column("refresh_token", sa.String(length=255), nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_app_connection_refresh_token"),
            ["refresh_token"],
            unique=False,
        )
        batch_op.create_unique_constraint("unique_access_token", ["access_token"])

    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_app_id", UUID(), nullable=False))
        batch_op.create_foreign_key(
            "nwc_connection_client_app_fk", "client_app", ["client_app_id"], ["id"]
        )
        batch_op.drop_column("app_name")
        batch_op.drop_column("description")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("app_name", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_constraint("nwc_connection_client_app_fk", type_="foreignkey")
        batch_op.drop_column("client_app_id")

    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.drop_constraint("unique_access_token", type_="unique")
        batch_op.drop_index(batch_op.f("ix_app_connection_refresh_token"))
        batch_op.drop_column("refresh_token")
        batch_op.drop_column("access_token")

    op.drop_table("client_app")
    # ### end Alembic commands ###
