"""update AppConnection

Revision ID: 10ffe99e7310
Revises: c6fd2a79bb65
Create Date: 2024-08-21 15:27:48.522531

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10ffe99e7310"
down_revision: Union[str, None] = "c6fd2a79bb65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.drop_constraint("unique_client_id", type_="unique")
        batch_op.drop_constraint("app_connection_user_fk", type_="foreignkey")
        batch_op.drop_column("client_id")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.CHAR(length=32), nullable=False))
        batch_op.add_column(
            sa.Column("client_id", sa.VARCHAR(length=255), nullable=False)
        )
        batch_op.create_foreign_key(
            "app_connection_user_fk", "user", ["user_id"], ["id"]
        )
        batch_op.create_unique_constraint("unique_client_id", ["client_id"])

    # ### end Alembic commands ###
