"""make params in Nip47Request not nullable

Revision ID: 15d5b0a9bde9
Revises: 556f426aa133
Create Date: 2024-08-09 12:25:34.204447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '15d5b0a9bde9'
down_revision: Union[str, None] = '556f426aa133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nip47_request', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nip47_request', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
