"""create spending_cycle_payment table

Revision ID: 2c83a1c59b75
Revises: b2688d1a99a9
Create Date: 2024-09-06 11:50:51.350606

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from nwc_backend.db import UUID

# revision identifiers, used by Alembic.
revision: str = "2c83a1c59b75"
down_revision: Union[str, None] = "b2688d1a99a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spending_cycle_payment",
        sa.Column("nip47_request_id", UUID(), nullable=False),
        sa.Column("spending_cycle_id", UUID(), nullable=False),
        sa.Column("quote_id", UUID(), nullable=True),
        sa.Column("estimated_amount", sa.BigInteger(), nullable=False),
        sa.Column("budget_on_hold", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                name="paymentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("settled_amount", sa.BigInteger(), nullable=True),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="spending_cycle_payment_nip47_request_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["spending_cycle_quote.id"],
            name="spending_cycle_payment_quote_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["spending_cycle_id"],
            ["spending_cycle.id"],
            name="spending_cycle_payment_nip47_spending_cycle_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spending_cycle_payment")
    # ### end Alembic commands ###
