"""Add redirect_uri and code_challenge to connection

Revision ID: 4e3152f5f393
Revises: d94c732aa976
Create Date: 2024-09-17 18:31:47.568933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e3152f5f393"
down_revision: Union[str, None] = "d94c732aa976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("redirect_uri", sa.String(length=2048), nullable=True)
        )
        batch_op.add_column(
            sa.Column("code_challenge", sa.String(length=1024), nullable=True)
        )
        batch_op.alter_column(
            "authorization_code",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=1024),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "authorization_code",
            existing_type=sa.String(length=1024),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )
        batch_op.drop_column("code_challenge")
        batch_op.drop_column("redirect_uri")

    # ### end Alembic commands ###
