"""update multiple schema

Revision ID: 4ede705c5288
Revises: c34fdee83087
Create Date: 2024-08-06 10:04:47.851313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ede705c5288'
down_revision: Union[str, None] = 'c34fdee83087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_expiration', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('nostr_pubkey',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('nwc_connection_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('nwc_connection', schema=None) as batch_op:
        batch_op.alter_column('supported_commands',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('connection_expiration',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.alter_column('long_lived_vasp_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('long_lived_vasp_token_expiration',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('vasp_user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('uma_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('uma_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('vasp_user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('nwc_connection', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('long_lived_vasp_token_expiration',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('long_lived_vasp_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('connection_expiration',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('supported_commands',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('app_connection', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('nwc_connection_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.alter_column('nostr_pubkey',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('connection_expiration')

    # ### end Alembic commands ###
