"""Make long lived token nullable

Revision ID: 556f426aa133
Revises: aec6fad29025
Create Date: 2024-08-07 11:08:10.929681

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "556f426aa133"
down_revision: Union[str, None] = "aec6fad29025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "long_lived_vasp_token", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "long_lived_vasp_token_expiration",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "long_lived_vasp_token_expiration",
            existing_type=sa.DATETIME(),
            nullable=False,
        )
        batch_op.alter_column(
            "long_lived_vasp_token",
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
        )

    # ### end Alembic commands ###
