"""update nwc_connection table

Revision ID: 5d76da39d538
Revises: 22e5c17990be
Create Date: 2024-09-19 22:56:52.932004

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d76da39d538"
down_revision: Union[str, None] = "22e5c17990be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.drop_constraint(
            "nwc_connection_spending_limit_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "nwc_connection_spending_limit_id_deferrable_fkey",
            "spending_limit",
            ["spending_limit_id"],
            ["id"],
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        )
        batch_op.alter_column(
            "long_lived_vasp_token",
            existing_type=sa.VARCHAR(length=1024),
            nullable=False,
        )

    with op.batch_alter_table("spending_limit", schema=None) as batch_op:
        batch_op.drop_constraint(
            "spending_limit_nwc_connection_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "spending_limit_nwc_connection_id_deferrable_fkey",
            "nwc_connection",
            ["nwc_connection_id"],
            ["id"],
            initially="DEFERRED",
            deferrable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spending_limit", schema=None) as batch_op:
        batch_op.drop_constraint(
            "spending_limit_nwc_connection_id_deferrable_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "spending_limit_nwc_connection_id_fkey",
            "nwc_connection",
            ["nwc_connection_id"],
            ["id"],
        )
        batch_op.alter_column(
            "long_lived_vasp_token",
            existing_type=sa.VARCHAR(length=1024),
            nullable=True,
        )

    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.drop_constraint(
            "nwc_connection_spending_limit_id_deferrable_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "nwc_connection_spending_limit_id_fkey",
            "spending_limit",
            ["spending_limit_id"],
            ["id"],
        )

    # ### end Alembic commands ###
