"""outgoing_payment and payment_quote table

Revision ID: 74a57a029e89
Revises: 22e5c17990be
Create Date: 2024-09-20 15:38:43.064778

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from nwc_backend.db import UUID, DateTime

# revision identifiers, used by Alembic.
revision: str = "74a57a029e89"
down_revision: Union[str, None] = "22e5c17990be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_quote",
        sa.Column("nip47_request_id", UUID(), nullable=False),
        sa.Column("payment_hash", sa.String(length=255), nullable=False),
        sa.Column("sending_currency_code", sa.String(length=3), nullable=False),
        sa.Column("sending_currency_amount", sa.BigInteger(), nullable=False),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="payment_quote_nip47_request_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_hash", name="payment_quote_unique_payment_hash"),
    )
    op.create_table(
        "outgoing_payment",
        sa.Column("nip47_request_id", UUID(), nullable=False),
        sa.Column("quote_id", UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                name="paymentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("sending_currency_code", sa.String(length=3), nullable=False),
        sa.Column("sending_currency_amount", sa.BigInteger(), nullable=False),
        sa.Column("spending_cycle_id", UUID(), nullable=True),
        sa.Column("estimated_budget_currency_amount", sa.BigInteger(), nullable=True),
        sa.Column("budget_on_hold", sa.BigInteger(), nullable=True),
        sa.Column("settled_budget_currency_amount", sa.BigInteger(), nullable=True),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="outgoing_payment_nip47_request_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["payment_quote.id"],
            name="outgoing_payment_quote_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["spending_cycle_id"],
            ["spending_cycle.id"],
            name="outgoing_payment_spending_cycle_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("spending_cycle_payment")
    op.drop_table("spending_cycle_quote")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spending_cycle_quote",
        sa.Column("nip47_request_id", sa.CHAR(length=32), nullable=False),
        sa.Column("payment_hash", sa.VARCHAR(length=255), nullable=False),
        sa.Column("sending_currency_code", sa.VARCHAR(length=3), nullable=False),
        sa.Column("sending_currency_amount", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="spending_cycle_quote_nip47_request_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "payment_hash", name="spending_cycle_quote_unique_payment_hash"
        ),
    )
    op.create_table(
        "spending_cycle_payment",
        sa.Column("nip47_request_id", sa.CHAR(length=32), nullable=False),
        sa.Column("spending_cycle_id", sa.CHAR(length=32), nullable=False),
        sa.Column("quote_id", sa.CHAR(length=32), nullable=True),
        sa.Column("estimated_amount", sa.BIGINT(), nullable=False),
        sa.Column("budget_on_hold", sa.BIGINT(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=9), nullable=False),
        sa.Column("settled_amount", sa.BIGINT(), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="spending_cycle_payment_nip47_request_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["spending_cycle_quote.id"],
            name="spending_cycle_payment_quote_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["spending_cycle_id"],
            ["spending_cycle.id"],
            name="spending_cycle_payment_spending_cycle_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("outgoing_payment")
    op.drop_table("payment_quote")
    # ### end Alembic commands ###
