"""Only have supported_commands

Revision ID: 7e53e98d93ba
Revises: 6425881f2240
Create Date: 2024-07-30 10:32:24.898927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e53e98d93ba"
down_revision: Union[str, None] = "6425881f2240"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("supported_commands", sa.Text(), nullable=True))
        batch_op.drop_column("required_commands")
        batch_op.drop_column("optional_commands")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("optional_commands", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("required_commands", sa.TEXT(), nullable=True))
        batch_op.drop_column("supported_commands")

    # ### end Alembic commands ###
