"""Bump string lengths for tokens

Revision ID: 8934fcddb325
Revises: 1b1ae08aba79
Create Date: 2024-09-04 14:37:17.585853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8934fcddb325"
down_revision: Union[str, None] = "1b1ae08aba79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "access_token",
            existing_type=sa.String(length=255),
            type_=sa.String(length=1024),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "refresh_token",
            existing_type=sa.String(length=255),
            type_=sa.String(length=1024),
            existing_nullable=False,
        )

    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "long_lived_vasp_token",
            existing_type=sa.String(length=255),
            type_=sa.String(length=1024),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "long_lived_vasp_token",
            existing_type=sa.String(length=1024),
            type_=sa.String(length=255),
            existing_nullable=True,
        )

    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "refresh_token",
            existing_type=sa.String(length=1024),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "access_token",
            existing_type=sa.String(length=1024),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
