"""make nip47_request.event_id unique

Revision ID: 8badfeb64975
Revises: dbf25c5a070f
Create Date: 2024-09-13 16:51:41.368861

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8badfeb64975"
down_revision: Union[str, None] = "dbf25c5a070f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nip47_request", schema=None) as batch_op:
        batch_op.create_unique_constraint("nip47_request_unique_event_id", ["event_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nip47_request", schema=None) as batch_op:
        batch_op.drop_constraint("nip47_request_unique_event_id", type_="unique")

    # ### end Alembic commands ###
