"""Update nwc_connection supported commands

Revision ID: 8fa5da72dc33
Revises: 8934fcddb325
Create Date: 2024-09-05 16:46:03.818573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql.json import JSONB

# revision identifiers, used by Alembic.
revision: str = "8fa5da72dc33"
down_revision: Union[str, None] = "8934fcddb325"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "granted_permissions_groups",
                sa.JSON().with_variant(JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=False,
            )
        )
        batch_op.drop_column("supported_commands")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "supported_commands",
                sa.JSON().with_variant(JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=False,
            )
        )
        batch_op.drop_column("granted_permissions_groups")

    # ### end Alembic commands ###
