"""Hash the auth code in storage.

Revision ID: 96dda77642f9
Revises: 0067f522683a
Create Date: 2025-02-21 17:56:58.925218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96dda77642f9"
down_revision: Union[str, None] = "0067f522683a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hashed_authorization_code", sa.String(length=1024), nullable=True
            )
        )
        batch_op.drop_constraint(
            "nwc_connection_unique_authorization_code", type_="unique"
        )
        batch_op.create_unique_constraint(None, ["hashed_authorization_code"])
        batch_op.drop_column("authorization_code")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("authorization_code", sa.VARCHAR(length=1024), nullable=True)
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint(
            "nwc_connection_unique_authorization_code", ["authorization_code"]
        )
        batch_op.drop_column("hashed_authorization_code")

    # ### end Alembic commands ###
