"""move budget_currency to nwc_connection

Revision ID: a15389988245
Revises: 3ddd75dea8cf
Create Date: 2024-09-27 23:00:55.911569

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from nwc_backend.db import DBCurrency

# revision identifiers, used by Alembic.
revision: str = "a15389988245"
down_revision: Union[str, None] = "3ddd75dea8cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("budget_currency", DBCurrency(), nullable=True))

    usd = '{"code": "USD", "symbol": "$", "name": "US Dollar", "decimals": 2}'
    if op.get_bind().engine.name == "sqlite":
        op.execute(f"UPDATE nwc_connection set budget_currency='{usd}';")
    else:
        op.execute(f"UPDATE nwc_connection set budget_currency='{usd}'::json;")

    with op.batch_alter_table("spending_cycle", schema=None) as batch_op:
        batch_op.drop_column("limit_currency")

    with op.batch_alter_table("spending_limit", schema=None) as batch_op:
        batch_op.drop_column("currency")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spending_limit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency", DBCurrency(), nullable=False))

    with op.batch_alter_table("spending_cycle", schema=None) as batch_op:
        batch_op.add_column(sa.Column("limit_currency", DBCurrency(), nullable=False))

    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.drop_column("budget_currency")

    # ### end Alembic commands ###
