"""create spending_cycle_quote table

Revision ID: b2688d1a99a9
Revises: cd3ede965c49
Create Date: 2024-09-06 10:56:19.844832

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from nwc_backend.db import UUID

# revision identifiers, used by Alembic.
revision: str = "b2688d1a99a9"
down_revision: Union[str, None] = "cd3ede965c49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spending_cycle_quote",
        sa.Column("nip47_request_id", UUID(), nullable=False),
        sa.Column("payment_hash", sa.String(length=255), nullable=False),
        sa.Column("estimated_amount__amount", sa.BigInteger(), nullable=False),
        sa.Column("estimated_amount__currency", sa.String(length=3), nullable=False),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nip47_request_id"],
            ["nip47_request.id"],
            name="spending_cycle_quote_nip47_request_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "payment_hash", name="spending_cycle_quote_unique_payment_hash"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spending_cycle_quote")
    # ### end Alembic commands ###
