"""store nwc_connection_id on OutgoingPayment

Revision ID: b5c2515e5fd5
Revises: 74a57a029e89
Create Date: 2024-09-20 19:23:53.647841

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from nwc_backend.db import UUID

# revision identifiers, used by Alembic.
revision: str = "b5c2515e5fd5"
down_revision: Union[str, None] = "74a57a029e89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outgoing_payment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nwc_connection_id", UUID(), nullable=False))
        batch_op.create_index(
            "outgoing_payment_connection_id_status_created_at_idx",
            ["nwc_connection_id", "status", "created_at"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "outgoing_payment_nwc_connection_id_fkey",
            "nwc_connection",
            ["nwc_connection_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outgoing_payment", schema=None) as batch_op:
        batch_op.drop_constraint(
            "outgoing_payment_nwc_connection_id_fkey", type_="foreignkey"
        )
        batch_op.drop_index("outgoing_payment_connection_id_status_created_at_idx")
        batch_op.drop_column("nwc_connection_id")

    # ### end Alembic commands ###
