"""add unique to user.nostr_pubkey

Revision ID: b959cba00f93
Revises: 7e53e98d93ba
Create Date: 2024-07-29 16:43:05.385892

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b959cba00f93"
down_revision: Union[str, None] = "7e53e98d93ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "app_connection_nostr_pubkey_key", ["nostr_pubkey"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.drop_constraint("app_connection_nostr_pubkey_key", type_="unique")

    # ### end Alembic commands ###
