"""Add nwc connection and relationships

Revision ID: c34fdee83087
Revises: b959cba00f93
Create Date: 2024-08-02 14:07:56.290268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from nwc_backend.db import UUID


# revision identifiers, used by Alembic.
revision: str = "c34fdee83087"
down_revision: Union[str, None] = "b959cba00f93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nwc_connection",
        sa.Column("user_id", UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("supported_commands", sa.Text(), nullable=True),
        sa.Column("connection_expiration", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("max_budget_per_month", sa.Integer(), nullable=True),
        sa.Column("long_lived_vasp_token", sa.String(length=255), nullable=True),
        sa.Column(
            "long_lived_vasp_token_expiration",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nwc_connection_id", UUID(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "nwc_connection", ["nwc_connection_id"], ["id"]
        )
        batch_op.drop_column("supported_commands")
        batch_op.drop_column("max_budget_per_month")
        batch_op.drop_column("expires_at")
        batch_op.drop_column("user_id")
        batch_op.drop_column("long_lived_vasp_token")
        batch_op.drop_column("app_name")
        batch_op.drop_column("description")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("vasp_user_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("uma_address", sa.String(length=255), nullable=True)
        )
        batch_op.drop_constraint("unique_email", type_="unique")
        batch_op.create_unique_constraint("unique_uma_address", ["uma_address"])
        batch_op.create_unique_constraint("unique_vasp_user_id", ["vasp_user_id"])
        batch_op.drop_column("refresh_token")
        batch_op.drop_column("access_token")
        batch_op.drop_column("email")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(
            sa.Column("access_token", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("refresh_token", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_constraint("unique_uma_address", type_="unique")
        batch_op.drop_constraint("unique_vasp_user_id", type_="unique")
        batch_op.create_unique_constraint("unique_email", ["email"])
        batch_op.drop_column("uma_address")
        batch_op.drop_column("vasp_user_id")

    with op.batch_alter_table("app_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("app_name", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("long_lived_vasp_token", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("expires_at", sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(
            sa.Column("max_budget_per_month", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("supported_commands", sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])
        batch_op.drop_column("nwc_connection_id")

    op.drop_table("nwc_connection")
    # ### end Alembic commands ###
