"""update NwcConnection

Revision ID: c6fd2a79bb65
Revises: c4112caf7059
Create Date: 2024-08-21 13:40:40.067592

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql.json import JSONB

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6fd2a79bb65"
down_revision: Union[str, None] = "c4112caf7059"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.alter_column(
            "supported_commands",
            existing_type=sa.TEXT(),
            type_=sa.JSON().with_variant(JSONB(astext_type=sa.Text()), "postgresql"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "connection_expires_at", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.drop_column("long_lived_vasp_token_expiration")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("long_lived_vasp_token_expiration", sa.DATETIME(), nullable=True)
        )
        batch_op.alter_column(
            "connection_expires_at", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "supported_commands",
            existing_type=sa.JSON().with_variant(
                JSONB(astext_type=sa.Text()), "postgresql"
            ),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
