"""changes for manual connections

Revision ID: d94c732aa976
Revises: fd238818515f
Create Date: 2024-09-17 12:33:04.399818

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d94c732aa976"
down_revision: Union[str, None] = "fd238818515f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("custom_name", sa.String(length=255), nullable=True)
        )
        batch_op.alter_column(
            "client_app_id", existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.create_check_constraint(
            constraint_name="check_client_app_or_custom_name",
            condition="client_app_id IS NOT NULL OR custom_name IS NOT NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.drop_constraint("check_client_app_or_custom_name", type_="check")
        batch_op.alter_column(
            "client_app_id", existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.drop_column("custom_name")

    # ### end Alembic commands ###
