"""update spending_cycle_quote

Revision ID: dbf25c5a070f
Revises: 2c83a1c59b75
Create Date: 2024-09-13 14:12:44.940349

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbf25c5a070f"
down_revision: Union[str, None] = "2c83a1c59b75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spending_cycle_quote", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sending_currency_code", sa.String(length=3), nullable=False)
        )
        batch_op.add_column(
            sa.Column("sending_currency_amount", sa.BigInteger(), nullable=False)
        )
        batch_op.drop_column("estimated_amount__currency")
        batch_op.drop_column("estimated_amount__amount")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spending_cycle_quote", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("estimated_amount__amount", sa.BIGINT(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "estimated_amount__currency", sa.VARCHAR(length=3), nullable=False
            )
        )
        batch_op.drop_column("sending_currency_amount")
        batch_op.drop_column("sending_currency_code")

    # ### end Alembic commands ###
