"""create spending_limit table

Revision ID: ed85eb9c966f
Revises: 8fa5da72dc33
Create Date: 2024-09-06 00:13:19.603507

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from nwc_backend.db import UUID, DateTime

# revision identifiers, used by Alembic.
revision: str = "ed85eb9c966f"
down_revision: Union[str, None] = "8fa5da72dc33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spending_limit",
        sa.Column("nwc_connection_id", UUID(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "YEARLY",
                "NONE",
                name="spendinglimitfrequency",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("start_time", DateTime(), nullable=False),
        sa.Column("end_time", DateTime(), nullable=True),
        sa.Column("id", UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nwc_connection_id"],
            ["nwc_connection.id"],
            name="spending_limit_nwc_connection_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("spending_limit_id", UUID(), nullable=True))
        batch_op.create_foreign_key(
            "nwc_connection_spending_limit_id_fkey",
            "spending_limit",
            ["spending_limit_id"],
            ["id"],
        )
        batch_op.drop_column("spending_limit_amount")
        batch_op.drop_column("spending_limit_frequency")
        batch_op.drop_column("spending_limit_currency_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nwc_connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "spending_limit_currency_code", sa.VARCHAR(length=3), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("spending_limit_frequency", sa.VARCHAR(length=7), nullable=True)
        )
        batch_op.add_column(
            sa.Column("spending_limit_amount", sa.BIGINT(), nullable=True)
        )
        batch_op.drop_constraint(
            "nwc_connection_spending_limit_id_fkey", type_="foreignkey"
        )
        batch_op.drop_column("spending_limit_id")

    op.drop_table("spending_limit")
    # ### end Alembic commands ###
